"use strict";
exports.__esModule = true;
var ara_a_1 = require("./ara\u00F1a");
var gato_1 = require("./gato");
var listaDeAnimales_1 = require("./listaDeAnimales");
var pez_1 = require("./pez");
var animal1 = new gato_1.Gato(4, "michi", "esta jugando");
var animal2 = new ara_a_1.Araña(8);
var animal3 = new pez_1.Pez(0, "nemo", "no esta jugando");
var animal4 = new gato_1.Gato(4, "pepe", "no esta jusgando");
var arregloAnimales = [animal1, animal2, animal3];
var listadoA = new listaDeAnimales_1.ListadoDeAnimales(arregloAnimales);
var respuesta = listadoA.buscar(animal4);
console.log(respuesta);
listadoA.agregarAnimal(animal4);
var respuesta2 = listadoA.buscar(animal4);
console.log(respuesta2);
listadoA.removerAnimal(animal2);
var respuesta3 = listadoA.buscar(animal2);
console.log(respuesta3);
console.log(listadoA);
